# Generated by Django 5.1.1 on 2024-11-04 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='task',
            field=models.CharField(default='Default Task Description', max_length=255),
            preserve_default=False,
        ),
    ]
